### ISSUE TITLE
global install

### ISSUE THREAD

**Issue by DanielRuf** [andreineculau/npm-publish-git#3]
It would be good to have this globally.

**Comment by andreineculau** [comment]
I personally disagree with that statement. npm-publish-git is more of a package-driven tool (e.g. this package gets published to a git repo, it is being tested with jest, it is being transpiled from typescript etc), than a user-driven tool (I use npm/yarn/pnpm to publish, etc).

I know it's more in line with current practices as lots of utils advertise themselves as "just <npm i -g me>". But that has a plethora of issues, and on the top of the list is making sure that all the maintainers of package X (which uses npm-publish-git) use the same version of npm-publish-git.
